services:
  - type: web
    name: ai-gce-master
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_AI_KEY
        sync: false # You will fill this in the Render Dashboard
      - key: CAMPAY_TOKEN
        sync: false # You will fill this in the Render Dashboard
      - key: PYTHON_VERSION
        value: 3.10.0